#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Cleaning..."

  (
    set -x

    git remote remove "zboilerplate" 2>/dev/null || true

    # rm -rf "./build" Built products, do not clean!
    rm -rf ./**/*.generated.*
    rm -rf "./node_modules"
    rm -rf "./submodules/"*"/node_modules"
    rm -rf "./example/node_modules"
  )

}

main "$@"
