#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

# shellcheck source=./lib/bash/templates.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/templates.sh"

# shellcheck source=./lib/bash/node.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/node.sh"

dependency "shellcheck"

function main() {

  if [[ ! -d "./node_modules" ]]; then
    "./pipeline/install"
  fi

  echo -e "${OK_COLOR}==> Linting code..."

  applyEnvVarsToTemplateFiles || removeGeneratedFiles

  (
    set -x
    shellcheck \
      --external-sources \
      "./.bin/"* \
      "./lib/bash/"* \
      "./pipeline/"* ||
      shellcheck \
        "./.bin/"* \
        "./lib/bash/"* \
        "./pipeline/"*
  )

  NPM="$(command -v npm)"

  (
    set -x
    "${NPM}" run lint
  )

}

main "$@"
