#!/usr/bin/env bash

export BOILERPLATE_LOGGER="false" # For external CLIs with user interactions

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo
  echo -e "${OK_COLOR}==> Setting up project...${CLEAR_COLOR}"

  loadDotEnv

  # Git
  echo
  echo "Setting up Git..."

  local GIT_REMOTE_URL
  GIT_REMOTE_URL="$(git config --get remote.origin.url)"
  echo "GIT_REMOTE_URL = '${GIT_REMOTE_URL}'"

  local GIT_FOLDER_NAME="${GIT_REMOTE_URL##*/}"
  GIT_FOLDER_NAME="${GIT_FOLDER_NAME%.*}"
  echo "GIT_FOLDER_NAME = '${GIT_FOLDER_NAME}'"

  # EnvKey
  echo
  echo "Setting up runtime EnvKeys..."

  read -p "EnvKey for branch 'develop': " -r ENVKEY_DEVELOP
  printf "\n# Develop\n# ENVKEY=%s\n" "${ENVKEY_DEVELOP}" >>"./.env"

  read -p "EnvKey for branch 'master': " -r ENVKEY_MASTER
  printf "\n# Master\n# ENVKEY=%s\n" "${ENVKEY_MASTER}" >>"./.env"

}

main "$@"
